POST http://localhost:3003/api/notes/
Content-Type: application/json

{
	"content": "User ID of the note author is sent along the request",
	"important": true,
  "userId": "5ddf2f3495d5bd6c217d5082"
}